# Generated by Django 6.1 on 2026-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=150)),
                ('battery', models.CharField(blank=True, max_length=100)),
                ('display', models.CharField(blank=True, max_length=150)),
                ('gpu', models.CharField(blank=True, max_length=150)),
                ('camera', models.CharField(blank=True, max_length=150)),
                ('usage', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='Local Database', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
