# Generated by Django 6.1 on 2026-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_address_order_city_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=30),
        ),
    ]
